version: '3'
services:
  mysql:
    image: mysql:latest
    volumes:
      - "mysql_data:/var/lib/mysql"
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: leavemgmt
      MYSQL_USER: amit
      MYSQL_PASSWORD: password

  laravel-env:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    depends_on:
      - mysql
    volumes:
      - ".:/var/www/leavemgmtsys"

  nginx:
    image: nginx:latest
    volumes:
      - ./dockerfiles/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

    restart: always

volumes:
  mysql_data: